services:
  db:
    image: tracktor/postgres:17.5-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron"]
volumes:
  pgdata:
